""" add_fefo_sort_index_to_batches

Revision ID: 3ac1dfeaac26
Revises: 'f8fe01bb5199'
Create Date: 2026-08-15 21:18:17.872756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac1dfeaac26'
down_revision: Union[str, None] = 'f8fe01bb5199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_batches_fefo_sort', 'batches', ['expiry_date', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batches_fefo_sort', table_name='batches')
    # ### end Alembic commands ###
